### ISSUE TITLE
AzExtParentTreeItem typing does not include collapsibleState property

### ISSUE THREAD

**Issue by philliphoff** [microsoft/vscode-azuretools#804] opened 2020-09-18 05:18 UTC
The typing for `AzExtParentTreeItem` does not include the [`collapsibleState`](https://github.com/microsoft/vscode-azuretools/blob/1fd7c3318212deccae36f373250acb37fdfbbafa/ui/src/treeDataProvider/AzExtParentTreeItem.ts#L30) property.  Even though it works at runtime, it makes the compiler very unhappy.

**Comment by EricJizbaMSFT** [comment] 2020-09-18 18:15
@philliphoff any chance you can just submit a PR to fix this?

**Comment by bwateratmsft** [comment] 2020-09-24 13:51
I think this is a dupe of #631.

@philliphoff I did find a hacky way to set it at runtime, within the `AzExtParentTreeItem`'s constructor--
```typescript
(this as TreeItem).collapsibleState = TreeItemCollapsibleState.Expanded;
```

**Closed by bwateratmsft** 2020-09-24 13:51 UTC
