### ISSUE TITLE
Not detecting existing csproj

### ISSUE THREAD

**Issue by AtillaYadik** [Microsoft/vscode-azuretools#165] opened 2018-04-25 22:14 UTC
Repro steps:
<Enter steps to reproduce issue>

Action: azureFunctions.validateFunctionProjects
Error type: Error
Error Message: Expected to find a single "csproj" file in folder "Demo2", but found zero or multiple instead.

Version: Unknown
OS: win32

**Comment by EricJizbaMSFT** [comment] 2018-05-07 18:03
Thanks for reporting! Closing as dupe of https://github.com/Microsoft/vscode-azuretools/issues/164

**Closed by EricJizbaMSFT** 2018-05-07 18:03 UTC
